spring:
  application:
    name: JLoka Application
  datasource:
    url: jdbc:mariadb://localhost:3306/jloka_store?createDatabaseIfNotExist=true
    username: root
    password: 123
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

mail:
  host: JLoka
  port: 3000