spring:
  application:
    name: JLoka Application
  datasource:
    url: jdbc:mariadb://localhost:3306/jloka_store?createDatabaseIfNotExists=true
    username: root
    password: 123

stripe:
  apiUrl: https://api.stripe.com
  enabled: true
  timeout: 3000
  supported-currencies:
    - USD
    - EUR
    - GBP
payment-gateway: strip

mail:
  host: https://jloka.smtp.com
  port: 12345