spring:
  application:
    name: JLoka Application
stripe:
  apiUrl: https://api.stripe.com
  enabled: true
  timeout: 3000
  supported-currencies:
    - USD
    - EUR
    - GBP
payment-gateway: strip

mail:
  host: https://jloka.smtp.com
  port: 12345